// flow-typed signature: 89911c7db1e5dde5fda693bd7703cd81
// flow-typed version: <<STUB>>/@acuris/apollo_v^0.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@acuris/apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@acuris/apollo' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@acuris/apollo/flow-typed/npm/@acuris/oos-config_vx.x.x' {
    declare module.exports: any;
}

declare module '@acuris/apollo/flow-typed/npm/apollo-cache-inmemory_vx.x.x' {
    declare module.exports: any;
}

declare module '@acuris/apollo/flow-typed/npm/apollo-client_v2.x.x' {
    declare module.exports: any;
}

declare module '@acuris/apollo/flow-typed/npm/apollo-link_vx.x.x' {
    declare module.exports: any;
}

declare module '@acuris/apollo/flow-typed/npm/apollo-link-http_v1.2.x' {
    declare module.exports: any;
}

declare module '@acuris/apollo/flow-typed/npm/apollo-link-state_vx.x.x' {
    declare module.exports: any;
}

declare module '@acuris/apollo/flow-typed/npm/flow-bin_v0.x.x' {
    declare module.exports: any;
}

declare module '@acuris/apollo/flow-typed/npm/graphql-tag.x.x' {
    declare module.exports: any;
}

declare module '@acuris/apollo/src/client' {
    declare module.exports: any;
}

declare module '@acuris/apollo/src/index' {
    declare module.exports: any;
}

// Filename aliases
declare module '@acuris/apollo/flow-typed/npm/@acuris/oos-config_vx.x.x.js' {
    declare module.exports: $Exports<
        '@acuris/apollo/flow-typed/npm/@acuris/oos-config_vx.x.x'
    >;
}
declare module '@acuris/apollo/flow-typed/npm/apollo-cache-inmemory_vx.x.x.js' {
    declare module.exports: $Exports<
        '@acuris/apollo/flow-typed/npm/apollo-cache-inmemory_vx.x.x'
    >;
}
declare module '@acuris/apollo/flow-typed/npm/apollo-client_v2.x.x.js' {
    declare module.exports: $Exports<
        '@acuris/apollo/flow-typed/npm/apollo-client_v2.x.x'
    >;
}
declare module '@acuris/apollo/flow-typed/npm/apollo-link_vx.x.x.js' {
    declare module.exports: $Exports<
        '@acuris/apollo/flow-typed/npm/apollo-link_vx.x.x'
    >;
}
declare module '@acuris/apollo/flow-typed/npm/apollo-link-http_v1.2.x.js' {
    declare module.exports: $Exports<
        '@acuris/apollo/flow-typed/npm/apollo-link-http_v1.2.x'
    >;
}
declare module '@acuris/apollo/flow-typed/npm/apollo-link-state_vx.x.x.js' {
    declare module.exports: $Exports<
        '@acuris/apollo/flow-typed/npm/apollo-link-state_vx.x.x'
    >;
}
declare module '@acuris/apollo/flow-typed/npm/flow-bin_v0.x.x.js' {
    declare module.exports: $Exports<
        '@acuris/apollo/flow-typed/npm/flow-bin_v0.x.x'
    >;
}
declare module '@acuris/apollo/flow-typed/npm/graphql-tag.x.x.js' {
    declare module.exports: $Exports<
        '@acuris/apollo/flow-typed/npm/graphql-tag.x.x'
    >;
}
declare module '@acuris/apollo/src/client.js' {
    declare module.exports: $Exports<'@acuris/apollo/src/client'>;
}
declare module '@acuris/apollo/src/index.js' {
    declare module.exports: $Exports<'@acuris/apollo/src/index'>;
}
