// flow-typed signature: 685db89bbecedfcfdb3b2321bfc71c36
// flow-typed version: <<STUB>>/@acuris/queries_v^0.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@acuris/queries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@acuris/queries' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@acuris/queries/src/index' {
  declare module.exports: any;
}

declare module '@acuris/queries/src/linkState' {
  declare module.exports: any;
}

declare module '@acuris/queries/src/server' {
  declare module.exports: any;
}

// Filename aliases
declare module '@acuris/queries/src/index.js' {
  declare module.exports: $Exports<'@acuris/queries/src/index'>;
}
declare module '@acuris/queries/src/linkState.js' {
  declare module.exports: $Exports<'@acuris/queries/src/linkState'>;
}
declare module '@acuris/queries/src/server.js' {
  declare module.exports: $Exports<'@acuris/queries/src/server'>;
}
