// flow-typed signature: bb394a9c9ae3885023202d92b8e9262c
// flow-typed version: <<STUB>>/@acuris/theme_v^0.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@acuris/theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@acuris/theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@acuris/theme/Colors' {
  declare module.exports: any;
}

declare module '@acuris/theme/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@acuris/theme/Fonts' {
  declare module.exports: any;
}

declare module '@acuris/theme/NativeMetrics' {
  declare module.exports: any;
}

declare module '@acuris/theme/WebMetrics' {
  declare module.exports: any;
}

declare module '@acuris/theme/WebStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module '@acuris/theme/Colors.js' {
  declare module.exports: $Exports<'@acuris/theme/Colors'>;
}
declare module '@acuris/theme/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@acuris/theme/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@acuris/theme/Fonts.js' {
  declare module.exports: $Exports<'@acuris/theme/Fonts'>;
}
declare module '@acuris/theme/index' {
  declare module.exports: $Exports<'@acuris/theme'>;
}
declare module '@acuris/theme/index.js' {
  declare module.exports: $Exports<'@acuris/theme'>;
}
declare module '@acuris/theme/NativeMetrics.js' {
  declare module.exports: $Exports<'@acuris/theme/NativeMetrics'>;
}
declare module '@acuris/theme/WebMetrics.js' {
  declare module.exports: $Exports<'@acuris/theme/WebMetrics'>;
}
declare module '@acuris/theme/WebStyles.js' {
  declare module.exports: $Exports<'@acuris/theme/WebStyles'>;
}
